### ISSUE TITLE
asioheaders raises warnings about `sprintf` on R-devel

### ISSUE THREAD

**Issue by wch** [eddelbuettel/asioheaders#8]
I received the following email from BDR, about the websocket package (https://github.com/rstudio/websocket/issues/99):

```
Subject: CRAN packages using AsioHeaders headers

See the check warnings for

ipaddress iptools websocket

Please liaise with the maintainer of the headers you use to get these
changed to use snprintf, or use your own versions.
```

If I understand correctly, asioheaders is bringing in `sprintf` to the compiled binaries for websocket. The websocket code base itself does not use `sprintf` anywhere, but the [CRAN check page](https://cran.r-project.org/web/checks/check_results_websocket.html) has the following:

```
Result: WARN
    File 'websocket/libs/websocket.so':
     Found 'sprintf', possibly from 'sprintf' (C)
     Object: 'websocket_connection.o'
    
    Compiled code should not call entry points which might terminate R nor
    write to stdout/stderr instead of to the console, nor use Fortran I/O
    nor system RNGs nor [v]sprintf.
```

`sprintf` does appear a few times in the asioheaders code base, though. For example:
https://github.com/eddelbuettel/asioheaders/blob/17e7dd15be867d596d23b369446638584f97f0d6/inst/include/asio/detail/impl/socket_ops.ipp#L2517

**Comment by eddelbuettel** [comment]
Will fix; a little strange he didn't email or CC me.  I had gotten one or two emails about residual `sprintf` use (even a single remaining use in `Rcpp` earlier) and fixed those.  

Looks like upstream is also a release ahead.

**Comment by eddelbuettel** [comment]
Looks like it's a few of them :-/  

```sh
edd@rob:~/git/asioheaders(master)$ ag sprintf
inst/include/asio/detail/impl/handler_tracking.ipp
362:  using namespace std; // For sprintf (or equivalent).
369:  int length = vsprintf_s(line, sizeof(line), format, args);
371:  int length = vsprintf(line, format, args);

inst/include/asio/detail/impl/win_static_mutex.ipp
42:  using namespace std; // For sprintf.

inst/include/asio/detail/impl/socket_ops.ipp
2410:  using namespace std; // For sprintf.
2414:    sprintf_s(dest, length, "%u.%u.%u.%u",
2426:        n += sprintf_s(dest + n, length - n, ":%s", b < 16 ? "" : ":"), ++z;
2430:        n += sprintf_s(dest + n, length - n, "%s%x", b ? ":" : "",
2436:      n += sprintf_s(dest + n, length - n, "%%%lu", scope_id);
2508:    using namespace std; // For strcat and sprintf.
2517:      sprintf(if_name + 1, "%lu", scope_id);
3626:      sprintf_s(serv, servlen, "%u", ntohs(port));
3628:      sprintf(serv, "%u", ntohs(port));
3649:        sprintf_s(serv, servlen, "%u", ntohs(port));
3651:        sprintf(serv, "%u", ntohs(port));

inst/include/asio/ip/impl/network_v4.ipp
129:  using namespace std; // For sprintf.
133:  sprintf_s(prefix_len, sizeof(prefix_len), "/%u", prefix_length_);
135:  sprintf(prefix_len, "/%u", prefix_length_);

inst/include/asio/ip/impl/network_v6.ipp
98:  using namespace std; // For sprintf.
102:  sprintf_s(prefix_len, sizeof(prefix_len), "/%u", prefix_length_);
104:  sprintf(prefix_len, "/%u", prefix_length_);

inst/include/asio/impl/connect_pipe.ipp
48:  using namespace std; // For sprintf and memcmp.
edd@rob:~/git/asioheaders(master)$ 
```

**Comment by eddelbuettel** [comment]
And 1.23 and 1.24 changes don't reference nuking `sprintf` :disappointed: 

https://think-async.com/Asio/asio-1.24.0/doc/asio/history.html#asio.history.asio_1_24_0

**Comment by eddelbuettel** [comment]
Can you actually replicate the issues CRAN has?

**Comment by wch** [comment]
I haven't tried locally yet, but hopefully I'll have time to try it in the next few days.

**Comment by eddelbuettel** [comment]
I realized I needed clang-15 from Debian unstable/testing and when I tried it first using `r-base` ... it did not reproduce because we also need r-devel.  When I retried again with `rocker/drd` I hit a (temporary) inconsistency at Debian where parts of the clang-15 package group were updated but others weren't.  Rare, but I have seen it happen.  Repo will sort itself out.   And then with r-devel on a recent Debian (ie newer than Ubuntu 22.04) it should reproduce. 

I think I may just monkey-patch asioheaders to get rid of the warnings for those three packages.  Note that clang-14 already yelled quite a bit about `websockets` requiring `-Wno-unused-but-set-variable -Wno-delete-non-abstract-non-virtual-dtor`.  The second one may be `asioheaders` fault.

**Comment by wch** [comment]
This will reproduce the warning:

```
docker run --rm -ti wch1/r-devel
git clone https://github.com/rstudio/websocket.git
RD -e "install.packages(c('cpp11', 'AsioHeaders', 'later', 'R6'))"
RD CMD build websocket
RD CMD check websocket_1.4.1.9000.tar.gz
```


The output includes:

```
* checking compiled code ... WARNING
File ‘websocket/libs/websocket.so’:
  Found ‘sprintf’, possibly from ‘sprintf’ (C)
    Object: ‘websocket_connection.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs nor [v]sprintf.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```

**Comment by eddelbuettel** [comment]
I presume that has clang-15 ?  Or does it reproduce with gcc too in which case I could just use my local r-devel ...

_Edit 1:_ Actually I think I can answer that myself as CRAN list four systems so gcc-12 will likely to it too.

_Edit 2:_ Negative. r-devel and gcc-12 is not sufficient.

```sh
edd@rob:/tmp/websocket$ RD CMD INSTALL -l lib/ websocket_1.4.1.tar.gz 
* installing *source* package ‘websocket’ ...
** package ‘websocket’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lssl -lcrypto
** libs
ccache g++-12  -std=gnu++11 -I"/usr/local/lib/R-devel/lib/R/include" -DNDEBUG -I./lib  -I'/tmp/websocket/lib/cpp11/include' -I'/tmp/websocket/lib/AsioHeaders/include' -I'/tmp/websocket/lib/later/include' -I/usr/local/include    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes -flto -c cpp11.cpp -o cpp11.o
ccache g++-12  -std=gnu++11 -I"/usr/local/lib/R-devel/lib/R/include" -DNDEBUG -I./lib  -I'/tmp/websocket/lib/cpp11/include' -I'/tmp/websocket/lib/AsioHeaders/include' -I'/tmp/websocket/lib/later/include' -I/usr/local/include    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes -flto -c debug.cpp -o debug.o
ccache g++-12  -std=gnu++11 -I"/usr/local/lib/R-devel/lib/R/include" -DNDEBUG -I./lib  -I'/tmp/websocket/lib/cpp11/include' -I'/tmp/websocket/lib/AsioHeaders/include' -I'/tmp/websocket/lib/later/include' -I/usr/local/include    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes -flto -c websocket.cpp -o websocket.o
ccache g++-12  -std=gnu++11 -I"/usr/local/lib/R-devel/lib/R/include" -DNDEBUG -I./lib  -I'/tmp/websocket/lib/cpp11/include' -I'/tmp/websocket/lib/AsioHeaders/include' -I'/tmp/websocket/lib/later/include' -I/usr/local/include    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes -flto -c websocket_connection.cpp -o websocket_connection.o
ccache g++-12  -std=gnu++11 -I"/usr/local/lib/R-devel/lib/R/include" -DNDEBUG -I./lib  -I'/tmp/websocket/lib/cpp11/include' -I'/tmp/websocket/lib/AsioHeaders/include' -I'/tmp/websocket/lib/later/include' -I/usr/local/include    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes -flto -c websocket_task.cpp -o websocket_task.o
websocket_connection.cpp: In function ‘cpp11::raws to_raw(std::string)’:
websocket_connection.cpp:37:17: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
   37 |   for(int i=0; i<input.size(); i++) {
      |                ~^~~~~~~~~~~~~
ccache g++-12 -std=gnu++11 -Wl,-S -shared -L/usr/local/lib/R-devel/lib/R/lib -L/usr/local/lib -o websocket.so cpp11.o debug.o websocket.o websocket_connection.o websocket_task.o -lssl -lcrypto -L/usr/local/lib/R-devel/lib/R/lib -lR
lto-wrapper: warning: using serial compilation of 14 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
installing to /tmp/websocket/lib/00LOCK-websocket/00new/websocket/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (websocket)
edd@rob:/tmp/websocket$ 
```

**Comment by wch** [comment]
Looks like it's still using gcc 10.

```
root@03128c62400c:/# gcc --version
gcc (Ubuntu 10.4.0-4ubuntu1~22.04) 10.4.0
```

This is where it's configured in the Dockerfile:
https://github.com/wch/r-debug/blob/master/r-devel/Dockerfile#L78-L79

**Comment by wch** [comment]
The Docker image uses a build of R-devel from yesterday:

```
root@03128c62400c:/# RD --version
R Under development (unstable) (2022-12-06 r83409) -- "Unsuffered Consequences"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```


Note that I don't see the `sprintf` warnings when running `RD CMD INSTALL`. They only show up when `RD CMD check` is run. 

I think it basically just greps the .so files for various strings. The new check was added in this commit:
https://github.com/wch/r-source/commit/a0dfa3df365e3ee2b4496fc2374963ff20da7043

**Comment by eddelbuettel** [comment]
> Note that I don't see the sprintf warnings when running RD CMD INSTALL. They only show up when RD CMD check is run.

Gee. Younger Dirk also knew that at some point. I guess I was in a rush.  Will try again later.

I let myself be mislead by the clang-15 on the CRAN table for their machines / setup. It is indeed 'just' R code checking.

**Comment by eddelbuettel** [comment]
Upstream addressed this two days ago: https://github.com/chriskohlhoff/asio/commit/1a2dd21c9865bb3e16829551b5e4c030bd743741

I had just done some first trial-and-error attempt and seemingly fixed your problem by addressing the one sprintf that is not inside an `#if WINDOWS`.  Carrying his patch over is likely easiest / cleanest.

**Comment by wch** [comment]
It's great to hear that it's been addressed upstream. Good timing!

**Comment by eddelbuettel** [comment]
Oddly, the one line I had found and fixed was not in that commit, so I added it by hand. I am now looking at `ipaddress` and `iptools` ; with a bit of luck this may get sorted out in due course.

**Comment by eddelbuettel** [comment]
No luck.  `ipaddress` still gives me 

```sh
* checking compiled code ... WARNING
File ‘ipaddress/libs/ipaddress.so’:
  Found ‘__sprintf_chk’, possibly from ‘sprintf’ (C)
    Objects: ‘ip_address.o’, ‘ip_network.o’, ‘ip_to_hex.o’,
      ‘reverse_pointer.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs nor [v]sprintf.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking installed files from ‘inst/doc’ ... OK
```

I think I now invested what can be considered a fair amount of time in this; and I may have to turn my attention to other matters.  It may be best to involve upstream in this.  This is really an upstream issue, and not a package issue.

**Comment by eddelbuettel** [comment]
Ok -- per Occam's Razor those issues in `iptools` and `ipaddress` were actually ... local to those packages and easy-ish to fix.   I am now reasonably confident that we have this sorted, and will send an updated `AsioHeaders` to CRAN. And small PRs to those two packages.

So you win because `websocket` didn't need fixes.  :wink:

**Comment by wch** [comment]
Great, and thanks for your efforts!

**Comment by eddelbuettel** [comment]
AsioHeaders 1.22.1-2 is now on CRAN.  Please reopen this if the issue persists, but this should now be addressed.  Thanks for the heads-up and the helpful discussion (and the reminder on how to actually reproduce it).
