### ISSUE TITLE
CRAN check encounters compilation warnings (r-release-macos)

### ISSUE THREAD

**Issue by davidchall** [eddelbuettel/asioheaders#9]
The ipaddress package encounters [CRAN check warnings](https://cran.r-project.org/web/checks/check_results_ipaddress.html) on r-release-macos, caused by compilation warnings from AsioHeaders:

```
Found the following significant warnings:
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/associated_allocator.hpp:100:49: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/execution/any_executor.hpp:611:47: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/io_context.hpp:231:36: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/io_context.hpp:856:43: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/io_context.hpp:859:37: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/io_context.hpp:860:29: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/system_executor.hpp:171:54: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/system_executor.hpp:175:28: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/system_executor.hpp:444:45: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/system_context.hpp:39:12: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
    /Volumes/Builds/packages/big-sur-arm64/Rlib/4.3/AsioHeaders/include/asio/detail/recycling_allocator.hpp:97:30: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
```

I suspect these warnings started appearing because CRAN have updated their compiler toolchain on r-release-macos, but I don't have further details. Do you have advice on how to resolve these, or will this require a new release of AsioHeaders?

**Comment by eddelbuettel** [comment]
Hi @davidchall thanks for posting this.  Now I don't quite recall _what_ I saw but I think i saw some package somewhere having an issue.  Maybe it was yours (scratches chin...).   

The best best is probably to look upstream if there is a fix 'for free' in a new release. I apparently last upgrade in June of 2022 to 1.22.1 (and I recall upstream was somewhat quiet leading up to it).    But I now see 1.28.0 at https://think-async.com/Asio/ so that will _likely_ fix it.   I will try to address this 'pronto' but I have a few other changes on my plate due to the format string checks added by r-devel.  If you happen to have spare cycles help with a PR would be great.  As I recall it is mostly a matter of copying / rsyncing the files in and then running a rev.dep check.

**Comment by davidchall** [comment]
Hi @eddelbuettel - Unfortunately, I still see `allocator<void>` in the master branch: 
https://github.com/chriskohlhoff/asio/blob/fa27820c05afd740fa2adc1ecfb9da5afe026443/asio/include/asio/associated_allocator.hpp#L113

It appears some users have encountered this compiler warning since Jan 2021: https://github.com/chriskohlhoff/asio/issues/785

*Update:* Asio author says the compilation warning is wrong: https://github.com/chriskohlhoff/asio/issues/290#issuecomment-377727614

**Comment by eddelbuettel** [comment]
Ouch.  Now we need a little bit of creative thinking ....

**Comment by davidchall** [comment]
Hi @eddelbuettel - I think I have a better understanding of what's gone wrong now.

* C++17 deprecated `std::allocator<void>` when used in explicit template specialization. But Asio does not fall under this use case.
* A few years ago, the MS compiler started raising warnings about any `std::allocator<void>` usage (false positives). This issue was fixed later.  [See VS ticket for details.](https://developercommunity.visualstudio.com/t/boost-asio-reports-stdallocator-is-deprecated-in-c/500588)
    * The Asio author replied to this issue here: https://github.com/chriskohlhoff/asio/issues/290#issuecomment-377727614
* More recently, the Apple compiler made the same mistake. This has now also been fixed. [See LLVM ticket for details.](https://bugs.llvm.org/show_bug.cgi?id=50299)
    * The Asio author replied to this issue here: https://github.com/boostorg/asio/issues/376#issuecomment-843632407


Here are the latest recommendations:
> In the meantime, please suppress deprecation warnings in your project settings, i.e. define _LIBCPP_DISABLE_DEPRECATION_WARNINGS. Or alternatively, upgrade to latest Xcode and compile with -std=c++20.

But I'm still not sure what's the best approach for CRAN. My understanding is that they typically don't want us to suppress compiler warnings.

**Comment by eddelbuettel** [comment]
They don't but they only control for what they can control for -- usually they check (via `grep` ie regexp from R) for the e.g.

     # pragma GCC diagnostic ignored "-Wnon-virtual-dtor"

I need to comment out for `BH`.  On the other hand I still have _global_ suppressor of nags for `Armadilo` on in `RcppArmadillo` "but they do not know" as you'd need semantic analysis per LSP or `clangd` or whatever.

So I think we're good.  Can you try the #define locally?

**Comment by davidchall** [comment]
Hi @eddelbuettel - In https://github.com/davidchall/ipaddress/pull/95, I've successfully reproduced the macOS compiler warning ([build](https://github.com/davidchall/ipaddress/actions/runs/7042064895/job/19165618058)). Then in the following commit I've silenced the warning by adding the macro to the Makevars file ([build](https://github.com/davidchall/ipaddress/actions/runs/7042327452/job/19166313334)).

I think this is what you asked me to confirm. Are the next steps for you to incorporate this macro into AsioHeaders?

**Comment by eddelbuettel** [comment]
Spot on.  I suspect we can do that centrally via a PR (but then need to remember to patch each time going forward).  Or is recommending to add to `Makevars` "good enough"  and it remains in client packages?  Just thinking out aloud.  

Thoughts?

**Comment by davidchall** [comment]
My preference is to add this to AsioHeaders for a couple of reasons:
1. Keeping the fix located with the source allows downstream package developers to use AsioHeaders transparently.
2. Enabling the macro in a header file provides an opportunity to add conditional logic (e.g., operating system, compiler), so it's only enabled where necessary.

Regarding repeated patches, I suspect (perhaps naively) this will be a one-time patch, because:
1. Historically, AsioHeaders doesn't update the underlying Asio frequently (previous update was July 2020),
2. When CRAN next updates its macOS toolchain, this issue will likely resolve.

**Comment by eddelbuettel** [comment]
Are we talking about the same thing?   `inst/include/` only contains upstream files.  Hence the need to patch. 

Or am I missing something?  Apologies if I do as I have my head in multiple concurrent conversations ...

**Comment by eddelbuettel** [comment]
So _one_ way around it (via the beloved [Fundamental Theorem of Software Engineering](https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering)) would be to add a new header which includes the `#define` before including the default asio header(s).

**Comment by davidchall** [comment]
> Are we talking about the same thing? `inst/include/` only contains upstream files. Hence the need to patch.
> 
> Or am I missing something? Apologies if I do as I have my head in multiple concurrent conversations ...

Sorry if I made this confusing. Here's my expectation of how this could work:
1. [Optional] AsioHeaders updates bundled Asio to 1.28.0
2. AsioHeaders patches to conditionally define macro (perhaps at the top of each Asio header file?)
3. Publish new version of AsioHeaders
4. CRAN check warning is resolved for downstream packages (e.g., ipaddress)
5. [Optional] If AsioHeaders updates bundled Asio, will need to repeat patch
6. CRAN updates macOS toolchain, which resolves compiler warning
7. If AsioHeaders updates bundled Asio, patch no longer required

> So one way around it (via the beloved [Fundamental Theorem of Software Engineering](https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering)) would be to add a new header which includes the `#define` before including the default asio header(s).

This wouldn't work for ipaddress because it includes specific headers (not a default header). See [code search results](https://github.com/search?q=repo%3Adavidchall%2Fipaddress+include+asio&type=code).

**Comment by eddelbuettel** [comment]
Can you not separate out the `#define` you need and do it your end?

I would love to be responsible for fewer recurring steps if I can.  Maybe I do codesearch later to see how other users of the package pull it in.

**Comment by eddelbuettel** [comment]
There are two reverse dependencies (both `LinkingTo`) for `AsioHeaders`: your `ipaddress`, and Winston's `websocket`.

I think adding a simple `-D.....` to their respective `Makevars` is a pretty attractive option that closes this issue.

**Comment by davidchall** [comment]
Yeah, I initially thought that was like using a sledgehammer to hit a nail, but it's much simpler than the other options. I'll go with that.

**Comment by eddelbuettel** [comment]
It's also more robust.  You won't have to depend on me not forgetting to patch and all that.

And remind me again:  we only need this on macOS until the compiler updates?

**Comment by davidchall** [comment]
> And remind me again: we only need this on macOS until the compiler updates?

I believe so. I've not seen the warning from the default macOS image on GitHub Actions or my local machine, and these both use more recent toolchains. I had to manually override the macOS SDK path to force this warning to appear.

**Comment by eddelbuettel** [comment]
Can you think of a clever conditional way to inject the `#define` into `src/Makevars` only when needed?   For example I decided to play games [here where we pick C++14 only when needed (on R older than 4.2.0 which made it a defaul)](https://github.com/qlcal/qlcal-r/blob/master/tools/configure.R).  (That was mostly an exercise. Leaving it empty and letting people on older systems fight for themselves seems good enough for CRAN even if not technically good enough for all of us...)

**Comment by davidchall** [comment]
Unfortunately, I couldn't find a way to do it. So I plan to use the sledgehammer and keep an eye on when CRAN updates above "MacOSX11.3.sdk".

**Comment by eddelbuettel** [comment]
Yeppers so I think we are circling around 'unconditionally add the `#define`' as it helps where needed, does not harm otherwise, and is easy to administrate.

**Comment by eddelbuettel** [comment]
Would appear you have [a new version at CRAN](http://dirk.eddelbuettel.com/cranberries/2023/12/01#ipaddress_1.0.2) so closing this.
